services:
  # 1. API Web Service
  - type: web
    name: api
    env: docker
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    plan: free

  # 2. Prometheus Service
  - type: web
    name: prometheus
    env: docker
    dockerContext: .
    dockerfilePath: ./monitoring/prometheus.Dockerfile
    plan: free

  # 3. Grafana Web Service
  - type: web
    name: grafana
    env: docker
    dockerContext: .
    dockerfilePath: ./monitoring/grafana.Dockerfile
    plan: free
    envVars:
      - key: GF_DATABASE_TYPE
        value: postgres
      - key: GF_DATASOURCE_PROMETHEUS_URL
        value: https://prometheus.onrender.com
      - key: PROMETHEUS_URL
        value: https://prometheus-132t.onrender.com
      - key: GF_DATABASE_HOST
        fromDatabase:
          name: grafana-db
          property: host
      - key: GF_DATABASE_PORT
        fromDatabase:
          name: grafana-db
          property: port
      - key: GF_DATABASE_NAME
        fromDatabase:
          name: grafana-db
          property: database
      - key: GF_DATABASE_USER
        fromDatabase:
          name: grafana-db
          property: user
      - key: GF_DATABASE_PASSWORD
        fromDatabase:
          name: grafana-db
          property: password

databases:
  # Free-tier Postgres for Grafana session & dashboard persistence
  - name: grafana-db
    plan: free
