services:
  # 1. API Web Service
  - type: web
    name: api
    env: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: free

  # 2. Prometheus Private Service
  - type: pserv
    name: prometheus
    env: docker
    dockerContext: monitoring
    dockerfilePath: prometheus.Dockerfile
    plan: free

  # 3. Grafana Web Service
  - type: web
    name: grafana
    env: docker
    dockerContext: monitoring
    dockerfilePath: grafana.Dockerfile
    plan: free
    envVars:
      - key: GF_DATABASE_TYPE
        value: postgres
      - key: GF_DATABASE_HOST
        fromDatabase:
          name: grafana-db
          property: host
      - key: GF_DATABASE_PORT
        fromDatabase:
          name: grafana-db
          property: port
      - key: GF_DATABASE_NAME
        fromDatabase:
          name: grafanadb
          property: database
      - key: GF_DATABASE_USER
        fromDatabase:
          name: grafanadb
          property: user
      - key: GF_DATABASE_PASSWORD
        fromDatabase:
          name: grafanadb
          property: password

databases:
  # Free-tier Postgres for Grafana session & dashboard persistence
  - name: grafana-db
    plan: free
